### PR TITLE
Add simple object example to README

### PR DESCRIPTION
**Pull request by cymen**
Add a simple object example to the README. I was guessing which order the parameters so...

Thanks!

### CODE REVIEW

**Comment by cymen** [comment]
Argh... Bitten by this again. @DamonOehlman is there any reason this can't be merged in? I came back to see if I should open a PR to update the docs and found I'd opened one already!

**Comment by DamonOehlman** [comment]
Nope - I think I probably just missed this first time around.  I'll merge it in tonight.

**Comment by DamonOehlman** [comment]
All merged in.  I've done a few tweaks to I don't accidentally overwrite the example at a later date (I generate the docs from source).  Thanks again for making the PR and reminding me about it...

**Comment by cymen** [comment]
@DamonOehlman Thank you!

**Pull request merged**
